services:
  - type: web
    name: e-comers-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://e-commers-backend.onrender.com
      - key: BACKEND_URL
        value: https://e-commers-backend.onrender.com
